### ISSUE TITLE
TypeError: ConnectionError() takes no keyword arguments

### ISSUE THREAD

**Issue by delobanov** [romis2012/python-socks#37]
Hello! 

Sometimes I get error `TypeError: ConnectionError() takes no keyword arguments` when trying to connect to proxy. 
This exception raises when `python_socks._protocols.errors.ReplyError: Host unreachable` also raised. 

Full stack trace. Is that error is because of bug in library?

```
 + Exception Group Traceback (most recent call last):
  |   File "/opt/telegram_client/src/scripts/load_new_accounts.py", line 170, in <module>
  |     asyncio.run(main())
  |   File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
  |     return runner.run(main)
  |            ^^^^^^^^^^^^^^^^
  |   File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
  |     return self._loop.run_until_complete(task)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
  |     return future.result()
  |            ^^^^^^^^^^^^^^^
  |   File "/opt/telegram_client/src/scripts/load_new_accounts.py", line 161, in main
  |     async with asyncio.TaskGroup() as tg:
  |   File "/usr/lib/python3.12/asyncio/taskgroups.py", line 145, in __aexit__
  |     raise me from None
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/opt/telegram_client/.venv/lib/python3.12/site-packages/python_socks/async_/asyncio/_proxy.py", line 93, in _connect
    |     await connector.connect(
    |   File "/opt/telegram_client/.venv/lib/python3.12/site-packages/python_socks/_connectors/socks5_async.py", line 79, in connect
    |     reply: socks5.ConnectReply = conn.receive(data)
    |                                  ^^^^^^^^^^^^^^^^^^
    |   File "/opt/telegram_client/.venv/lib/python3.12/site-packages/python_socks/_protocols/socks5.py", line 347, in receive
    |     reply = ConnectReply.loads(data)
    |             ^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/opt/telegram_client/.venv/lib/python3.12/site-packages/python_socks/_protocols/socks5.py", line 209, in loads
    |     raise ReplyError(msg, error_code=reply)
    | python_socks._protocols.errors.ReplyError: Host unreachable
    | 
    | During handling of the above exception, another exception occurred:
    | 
    | Traceback (most recent call last):
    |   File "/opt/telegram_client/src/scripts/load_new_accounts.py", line 103, in prepare_account
    |     await client.connect()
    |   File "/opt/telegram_client/.venv/lib/python3.12/site-packages/telethon/client/telegrambaseclient.py", line 547, in connect
    |     if not await self._sender.connect(self._connection(
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/opt/telegram_client/.venv/lib/python3.12/site-packages/telethon/network/mtprotosender.py", line 134, in connect
    |     await self._connect()
    |   File "/opt/telegram_client/.venv/lib/python3.12/site-packages/telethon/network/mtprotosender.py", line 234, in _connect
    |     connected = await self._try_connect(attempt)
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/opt/telegram_client/.venv/lib/python3.12/site-packages/telethon/network/mtprotosender.py", line 284, in _try_connect
    |     await self._connection.connect(timeout=self._connect_timeout)
    |   File "/opt/telegram_client/.venv/lib/python3.12/site-packages/telethon/network/connection/connection.py", line 244, in connect
    |     await self._connect(timeout=timeout, ssl=ssl)
    |   File "/opt/telegram_client/.venv/lib/python3.12/site-packages/telethon/network/connection/connection.py", line 225, in _connect
    |     sock = await self._proxy_connect(
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/opt/telegram_client/.venv/lib/python3.12/site-packages/telethon/network/connection/connection.py", line 135, in _proxy_connect
    |     sock = await proxy.connect(
    |            ^^^^^^^^^^^^^^^^^^^^
    |   File "/opt/telegram_client/.venv/lib/python3.12/site-packages/python_socks/async_/asyncio/_proxy.py", line 59, in connect
    |     return await self._connect(
    |            ^^^^^^^^^^^^^^^^^^^^
    |   File "/opt/telegram_client/.venv/lib/python3.12/site-packages/python_socks/async_/asyncio/_proxy.py", line 108, in _connect
    |     raise ProxyError(e, error_code=e.error_code)
    |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    | TypeError: ConnectionError() takes no keyword arguments
    +------------------------------------

```

**Comment by romis2012** [comment]
> TypeError: ConnectionError() takes no keyword arguments

`pythons-socks` does not raise this exception at all. 
May be the problem is in an external package that uses `pythons-socks`

**Comment by delobanov** [comment]
Found what telethon monkey-patch your errors like
```
        if python_socks:
            # python_socks internal errors are not inherited from
            # builtin IOError (just from Exception). Instead of adding those
            # in exceptions clauses everywhere through the code, we
            # rather monkey-patch them in place.

            python_socks._errors.ProxyError = ConnectionError
            python_socks._errors.ProxyConnectionError = ConnectionError
            python_socks._errors.ProxyTimeoutError = ConnectionError
```
Problem is not into your library. Sorry to bother.
